pickUpPoint:
  x: 21
  y: 0
  z: 10
sortingPoints:
- name: test
  points:
    x: 203
    y: -10.8
    z: 0.5
  expression: colour:yellow
- name: bla
  points:
    x: 14
    y: 15
    z: 0
  expression: (colour:blue&shape:triangle)|(!colour:yellow&shape:square)
